export const LOAD_FLIGHT_DETAILS = "LOAD_FLIGHT_DETAILS";
export const LOAD_PASSENGER_DETAILS = "LOAD_PASSENGER_DETAILS";
export const UPDATE_PASSENGER_DETAILS = "UPDATE_PASSENGER_DETAILS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
